"""
Adversarial Perturbation Strategy (APS) experiment for CIFAR-10.

This script trains two victim-side models:

1. A model on the clean training set.
2. A model on the same training set with selected samples replaced by the
   label-consistent APS images generated by Generate_Perturbed_Images_APS.py.

During each victim training step it computes the first-order in-run data
Shapley increment:

    Delta phi_i = - learning_rate * <g_i, g_val>

where g_i is a per-sample training gradient and g_val is the validation loss
gradient. The resulting CSV files can be used to calculate Gain-Stealing,
Loss-Amplifying, and volatility statistics.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import Dict, List, Mapping, Optional, Sequence, Tuple

import torch
import torch.nn as nn
import torch.optim as optim
from torch.nn.utils import parameters_to_vector
from torch.utils.data import DataLoader, Subset
from torchvision import datasets

from APS_Common import (
    IndexedCIFAR10,
    ModifiedCIFARCNN,
    PoisonedCIFAR10Dataset,
    cifar10_normalize,
    load_image_tensor,
    make_cifar10_transform,
    set_seed,
)


def _flatten_gradient_dict(
    gradients: Mapping[str, torch.Tensor],
) -> torch.Tensor:
    return torch.cat(
        [gradient.reshape(gradient.size(0), -1) for gradient in gradients.values()],
        dim=1,
    )


def per_sample_grads(
    model: nn.Module,
    images: torch.Tensor,
    labels: torch.Tensor,
    criterion: nn.Module,
) -> torch.Tensor:
    """
    Compute one flattened parameter gradient per sample.

    ``torch.func.vmap`` is used when available. A small-batch autograd
    fallback keeps the script usable on older PyTorch versions.
    """

    try:
        from torch.func import functional_call, grad, vmap

        params = dict(model.named_parameters())
        buffers = dict(model.named_buffers())

        def loss_fn(
            functional_params,
            functional_buffers,
            image,
            label,
        ):
            logits = functional_call(
                model,
                (functional_params, functional_buffers),
                (image.unsqueeze(0),),
            )
            return criterion(logits, label.unsqueeze(0))

        gradients = vmap(grad(loss_fn), (None, None, 0, 0))(
            params,
            buffers,
            images,
            labels,
        )
        return _flatten_gradient_dict(gradients)
    except (ImportError, RuntimeError, TypeError):
        flat_gradients: List[torch.Tensor] = []
        parameters = tuple(
            parameter for parameter in model.parameters() if parameter.requires_grad
        )
        for image, label in zip(images, labels):
            logits = model(image.unsqueeze(0))
            loss = criterion(logits, label.unsqueeze(0))
            gradients = torch.autograd.grad(
                loss,
                parameters,
                create_graph=False,
                retain_graph=False,
                allow_unused=True,
            )
            flat_gradients.append(
                torch.cat(
                    [
                        torch.zeros_like(parameter).reshape(-1)
                        if gradient is None
                        else gradient.reshape(-1)
                        for parameter, gradient in zip(parameters, gradients)
                    ]
                )
            )
        return torch.stack(flat_gradients, dim=0)


def compute_validation_gradient(
    model: nn.Module,
    val_images: torch.Tensor,
    val_labels: torch.Tensor,
    criterion: nn.Module,
) -> torch.Tensor:
    """Compute the flattened validation loss gradient used by first-order IRDS."""

    parameters = tuple(
        parameter for parameter in model.parameters() if parameter.requires_grad
    )
    was_training = model.training
    model.train()
    try:
        logits = model(val_images)
        val_loss = criterion(logits, val_labels)
        gradients = torch.autograd.grad(
            val_loss,
            parameters,
            create_graph=False,
            retain_graph=False,
            allow_unused=True,
        )
        filled = [
            torch.zeros_like(parameter) if gradient is None else gradient
            for parameter, gradient in zip(parameters, gradients)
        ]
        return parameters_to_vector(filled).detach().unsqueeze(0)
    finally:
        model.train(was_training)


def evaluate(
    model: nn.Module,
    data_loader: DataLoader,
    criterion: nn.Module,
    device: torch.device,
) -> Tuple[float, float]:
    """Evaluate a model on a normal ``(image, label)`` data loader."""

    model.eval()
    total_loss = 0.0
    correct = 0
    total = 0
    with torch.no_grad():
        for images, labels in data_loader:
            images = images.to(device, non_blocking=True)
            labels = labels.to(device, non_blocking=True)
            logits = model(images)
            loss = criterion(logits, labels)
            total_loss += float(loss.item()) * labels.size(0)
            correct += int((logits.argmax(dim=1) == labels).sum().item())
            total += labels.size(0)
    return total_loss / max(total, 1), 100.0 * correct / max(total, 1)


def train_and_compute_shapley(
    model: nn.Module,
    train_loader: DataLoader,
    test_loader: DataLoader,
    optimizer: optim.Optimizer,
    criterion: nn.Module,
    epochs: int,
    device: torch.device,
    val_images: torch.Tensor,
    val_labels: torch.Tensor,
    result_dir: Path,
    shapley_filename: str,
    model_name: str,
    save_training_metrics: bool = False,
) -> Tuple[Path, List[float], List[float], List[float]]:
    """
    Train a victim model and compute first-order in-run data Shapley values.

    The validation gradient is computed before each optimizer update, matching
    the step-wise accumulation used by first-order IRDS.
    """

    result_dir.mkdir(parents=True, exist_ok=True)
    sample_count = len(train_loader.dataset)
    data_shapley = torch.zeros(sample_count, device=device)
    train_losses: List[float] = []
    test_losses: List[float] = []
    test_accuracies: List[float] = []
    print(f"Training {model_name} and accumulating first-order IRDS values...")

    for epoch in range(epochs):
        model.train()
        running_loss = 0.0
        correct = 0
        total = 0

        for indices, images, labels in train_loader:
            indices = indices.to(device, dtype=torch.long)
            images = images.to(device, non_blocking=True)
            labels = labels.to(device, non_blocking=True)

            sample_gradients = per_sample_grads(
                model=model,
                images=images,
                labels=labels,
                criterion=criterion,
            )
            validation_gradient = compute_validation_gradient(
                model=model,
                val_images=val_images,
                val_labels=val_labels,
                criterion=criterion,
            )
            learning_rate = float(optimizer.param_groups[0]["lr"])
            shapley_increment = -learning_rate * (
                sample_gradients @ validation_gradient.T
            ).squeeze(1)
            data_shapley[indices] += shapley_increment.detach()

            optimizer.zero_grad(set_to_none=True)
            logits = model(images)
            loss = criterion(logits, labels)
            loss.backward()
            optimizer.step()

            running_loss += float(loss.item()) * labels.size(0)
            correct += int((logits.argmax(dim=1) == labels).sum().item())
            total += labels.size(0)

        train_loss = running_loss / max(total, 1)
        train_accuracy = 100.0 * correct / max(total, 1)
        test_loss, test_accuracy = evaluate(
            model=model,
            data_loader=test_loader,
            criterion=criterion,
            device=device,
        )
        train_losses.append(train_loss)
        test_losses.append(test_loss)
        test_accuracies.append(test_accuracy)
        print(
            f"[{model_name}] Epoch {epoch + 1:03d}/{epochs:03d} | "
            f"Train Loss {train_loss:.4f} | Train Acc {train_accuracy:.2f}% | "
            f"Test Loss {test_loss:.4f} | Test Acc {test_accuracy:.2f}%"
        )

    shapley_path = result_dir / shapley_filename
    with shapley_path.open("w", newline="", encoding="utf-8") as output_file:
        writer = csv.writer(output_file)
        writer.writerow(["sample_index", "shapley_value"])
        for index, value in enumerate(data_shapley.detach().cpu().tolist()):
            writer.writerow([index, float(value)])

    if save_training_metrics:
        metrics_path = result_dir / f"training_metrics_{model_name.lower()}.csv"
        with metrics_path.open("w", newline="", encoding="utf-8") as output_file:
            writer = csv.writer(output_file)
            writer.writerow(["epoch", "train_loss", "test_loss", "test_accuracy"])
            for epoch, values in enumerate(
                zip(train_losses, test_losses, test_accuracies),
                start=1,
            ):
                writer.writerow([epoch, values[0], values[1], values[2]])

    print(f"{model_name} Shapley values saved to: {shapley_path}")
    return shapley_path, train_losses, test_losses, test_accuracies


def _read_shapley(path: Path) -> Dict[int, float]:
    values: Dict[int, float] = {}
    with path.open("r", newline="", encoding="utf-8") as input_file:
        reader = csv.DictReader(input_file)
        for row in reader:
            index_key = "sample_index" if "sample_index" in row else "index"
            values[int(row[index_key])] = float(row["shapley_value"])
    return values


def load_aps_images(
    output_root: Path,
    mapping_path: Path,
    expected_labels: Mapping[int, int],
) -> Dict[int, torch.Tensor]:
    """Load final APS images and normalize them for the victim model."""

    poisoned_images: Dict[int, torch.Tensor] = {}
    with mapping_path.open("r", newline="", encoding="utf-8") as mapping_file:
        reader = csv.DictReader(mapping_file)
        required = {"original_index", "label", "final_aps_image_path"}
        missing = required.difference(reader.fieldnames or [])
        if missing:
            raise ValueError(
                f"APS mapping is missing columns: {', '.join(sorted(missing))}"
            )
        for row in reader:
            index = int(row["original_index"])
            label = int(row["label"])
            if index in expected_labels and expected_labels[index] != label:
                raise ValueError(
                    f"Label mismatch for sample {index}: "
                    f"mapping={label}, original={expected_labels[index]}"
                )
            image_path = Path(row["final_aps_image_path"])
            if not image_path.is_absolute():
                image_path = output_root / image_path
            if not image_path.is_file():
                raise FileNotFoundError(f"APS image not found: {image_path}")
            pixel_image = load_image_tensor(image_path)
            poisoned_images[index] = cifar10_normalize(pixel_image)
    if not poisoned_images:
        raise ValueError(f"No APS samples found in mapping: {mapping_path}")
    return poisoned_images


def _save_optional_plot(
    result_dir: Path,
    train_losses: Sequence[float],
    test_losses: Sequence[float],
    accuracies: Sequence[float],
    model_name: str,
) -> None:
    """Save training curves when matplotlib is available."""

    try:
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib is unavailable; skipping training plot generation.")
        return

    figure = plt.figure(figsize=(12, 4))
    axis_loss = figure.add_subplot(1, 2, 1)
    axis_loss.plot(train_losses, label="Train Loss")
    axis_loss.plot(test_losses, label="Test Loss")
    axis_loss.set_title(f"{model_name} Loss")
    axis_loss.set_xlabel("Epoch")
    axis_loss.set_ylabel("Loss")
    axis_loss.legend()

    axis_accuracy = figure.add_subplot(1, 2, 2)
    axis_accuracy.plot(accuracies, label="Test Accuracy", color="green")
    axis_accuracy.set_title(f"{model_name} Test Accuracy")
    axis_accuracy.set_xlabel("Epoch")
    axis_accuracy.set_ylabel("Accuracy (%)")
    axis_accuracy.legend()
    figure.tight_layout()
    figure.savefig(result_dir / f"training_results_{model_name.lower()}.png")
    plt.close(figure)


def compute_attribution_metrics(
    original_shapley_path: Path,
    aps_shapley_path: Path,
    mapping_path: Path,
    result_dir: Path,
) -> Path:
    """
    Save directional attribution statistics for APS-selected samples.

    These are deliberately reported as simple directional rates. They do not
    replace the paper's full ASR/GSR/LAR protocol, but provide a transparent
    sanity check for the two Shapley files produced by this script.
    """

    original = _read_shapley(original_shapley_path)
    aps = _read_shapley(aps_shapley_path)
    selected_indices: List[int] = []
    with mapping_path.open("r", newline="", encoding="utf-8") as mapping_file:
        for row in csv.DictReader(mapping_file):
            selected_indices.append(int(row["original_index"]))

    rows: List[Tuple[int, float, float, float, int, int]] = []
    for index in selected_indices:
        if index not in original or index not in aps:
            continue
        original_value = original[index]
        aps_value = aps[index]
        delta = aps_value - original_value
        gain_stealing = int(aps_value < original_value)
        sign_flip = int(
            (original_value > 0.0 and aps_value < 0.0)
            or (original_value < 0.0 and aps_value > 0.0)
        )
        rows.append(
            (
                index,
                original_value,
                aps_value,
                delta,
                gain_stealing,
                sign_flip,
            )
        )

    metrics_path = result_dir / "aps_attribution_metrics.csv"
    with metrics_path.open("w", newline="", encoding="utf-8") as output_file:
        writer = csv.writer(output_file)
        writer.writerow(
            [
                "sample_index",
                "original_shapley",
                "aps_shapley",
                "delta_aps_minus_original",
                "directional_gain_stealing",
                "sign_flip",
            ]
        )
        writer.writerows(rows)

    total = len(rows)
    gain_rate = (
        sum(row[4] for row in rows) / total
        if total
        else 0.0
    )
    sign_flip_rate = (
        sum(row[5] for row in rows) / total
        if total
        else 0.0
    )
    print(
        f"APS attribution sanity check: {total} samples, "
        f"directional gain-stealing rate={gain_rate:.2%}, "
        f"sign-flip rate={sign_flip_rate:.2%}"
    )
    print(f"Attribution comparison saved to: {metrics_path}")
    return metrics_path


def _build_validation_batch(
    test_dataset: datasets.CIFAR10,
    validation_size: int,
    device: torch.device,
) -> Tuple[torch.Tensor, torch.Tensor]:
    validation_size = min(max(1, validation_size), len(test_dataset))
    subset = Subset(test_dataset, list(range(validation_size)))
    loader = DataLoader(subset, batch_size=validation_size, shuffle=False)
    images, labels = next(iter(loader))
    return images.to(device), labels.to(device)


def run_experiment(
    base_dir: Path,
    aps_root: Path,
    epochs: int = 100,
    batch_size: int = 64,
    learning_rate: float = 0.01,
    momentum: float = 0.9,
    validation_size: int = 128,
    seed: int = 42,
    num_workers: int = 0,
    skip_original: bool = False,
    skip_aps: bool = False,
    save_auxiliary_outputs: bool = False,
    evaluate_metrics: bool = False,
) -> None:
    """Run clean/APS victim training and first-order IRDS evaluation."""

    if skip_original and skip_aps:
        raise ValueError("At least one of skip_original and skip_aps must be False.")
    if epochs <= 0:
        raise ValueError("epochs must be positive.")

    set_seed(seed)
    base_dir = Path(base_dir)
    aps_root = Path(aps_root)
    mapping_path = aps_root / "aps_mapping.csv"
    if not mapping_path.is_file() and not skip_aps:
        raise FileNotFoundError(
            f"APS mapping not found: {mapping_path}. "
            "Run Generate_Perturbed_Images_APS.py first."
        )

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    data_dir = base_dir / "data" / "cifar10_data"
    result_dir = base_dir / "results_APS"
    result_dir.mkdir(parents=True, exist_ok=True)
    print(f"Victim IRDS experiment device: {device}")

    normalized_transform = make_cifar10_transform(normalize=True)
    clean_train_dataset = IndexedCIFAR10(
        root=str(data_dir),
        train=True,
        download=True,
        transform=normalized_transform,
    )
    test_dataset = datasets.CIFAR10(
        root=str(data_dir),
        train=False,
        download=True,
        transform=normalized_transform,
    )

    loader_generator = torch.Generator()
    loader_generator.manual_seed(seed)
    clean_train_loader = DataLoader(
        clean_train_dataset,
        batch_size=batch_size,
        shuffle=True,
        generator=loader_generator,
        num_workers=num_workers,
        pin_memory=device.type == "cuda",
    )
    test_loader = DataLoader(
        test_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=device.type == "cuda",
    )
    val_images, val_labels = _build_validation_batch(
        test_dataset,
        validation_size=validation_size,
        device=device,
    )
    criterion = nn.CrossEntropyLoss(reduction="mean")

    original_shapley_path: Optional[Path] = None
    aps_shapley_path: Optional[Path] = None

    if not skip_original:
        set_seed(seed)
        original_model = ModifiedCIFARCNN().to(device)
        original_optimizer = optim.SGD(
            original_model.parameters(),
            lr=learning_rate,
            momentum=momentum,
        )
        (
            original_shapley_path,
            train_losses,
            test_losses,
            accuracies,
        ) = train_and_compute_shapley(
            model=original_model,
            train_loader=clean_train_loader,
            test_loader=test_loader,
            optimizer=original_optimizer,
            criterion=criterion,
            epochs=epochs,
            device=device,
            val_images=val_images,
            val_labels=val_labels,
            result_dir=result_dir,
            shapley_filename="shapley_original_APS.csv",
            model_name="Original_APS",
            save_training_metrics=save_auxiliary_outputs,
        )
        if save_auxiliary_outputs:
            _save_optional_plot(
                result_dir,
                train_losses,
                test_losses,
                accuracies,
                "Original_APS",
            )

    if not skip_aps:
        labels_by_index = {
            index: int(clean_train_dataset[index][2])
            for index in range(len(clean_train_dataset))
        }
        poisoned_images = load_aps_images(
            output_root=aps_root,
            mapping_path=mapping_path,
            expected_labels=labels_by_index,
        )
        poisoned_dataset = PoisonedCIFAR10Dataset(
            original_dataset=clean_train_dataset,
            poisoned_images=poisoned_images,
        )
        aps_loader_generator = torch.Generator()
        aps_loader_generator.manual_seed(seed)
        aps_train_loader = DataLoader(
            poisoned_dataset,
            batch_size=batch_size,
            shuffle=True,
            generator=aps_loader_generator,
            num_workers=num_workers,
            pin_memory=device.type == "cuda",
        )

        set_seed(seed)
        aps_model = ModifiedCIFARCNN().to(device)
        aps_optimizer = optim.SGD(
            aps_model.parameters(),
            lr=learning_rate,
            momentum=momentum,
        )
        (
            aps_shapley_path,
            train_losses,
            test_losses,
            accuracies,
        ) = train_and_compute_shapley(
            model=aps_model,
            train_loader=aps_train_loader,
            test_loader=test_loader,
            optimizer=aps_optimizer,
            criterion=criterion,
            epochs=epochs,
            device=device,
            val_images=val_images,
            val_labels=val_labels,
            result_dir=result_dir,
            shapley_filename="shapley_aps.csv",
            model_name="APS",
            save_training_metrics=save_auxiliary_outputs,
        )
        if save_auxiliary_outputs:
            _save_optional_plot(
                result_dir,
                train_losses,
                test_losses,
                accuracies,
                "APS",
            )

    if (
        original_shapley_path is not None
        and aps_shapley_path is not None
        and evaluate_metrics
    ):
        compute_attribution_metrics(
            original_shapley_path=original_shapley_path,
            aps_shapley_path=aps_shapley_path,
            mapping_path=mapping_path,
            result_dir=result_dir,
        )

    print("APS victim-side IRDS experiment completed.")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train clean and APS-poisoned models and compute first-order IRDS."
    )
    parser.add_argument(
        "--base-dir",
        type=Path,
        default=Path("./xie/FNN_Shapley"),
    )
    parser.add_argument(
        "--aps-root",
        type=Path,
        default=None,
        help="Directory containing aps_mapping.csv; defaults to <base-dir>/aps_data.",
    )
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--batch-size", type=int, default=64)
    parser.add_argument("--learning-rate", type=float, default=0.01)
    parser.add_argument("--momentum", type=float, default=0.9)
    parser.add_argument("--validation-size", type=int, default=128)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--num-workers", type=int, default=0)
    parser.add_argument(
        "--skip-original",
        action="store_true",
        help="Only train/evaluate the APS-poisoned model.",
    )
    parser.add_argument(
        "--skip-aps",
        action="store_true",
        help="Only train/evaluate the clean model.",
    )
    parser.add_argument(
        "--save-auxiliary-outputs",
        action="store_true",
        help="Also save training curves and auxiliary training metrics.",
    )
    parser.add_argument(
        "--evaluate-metrics",
        action="store_true",
        help="Run the optional attribution comparison after producing both CSV files.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    aps_root = args.aps_root or (args.base_dir / "aps_data")
    run_experiment(
        base_dir=args.base_dir,
        aps_root=aps_root,
        epochs=args.epochs,
        batch_size=args.batch_size,
        learning_rate=args.learning_rate,
        momentum=args.momentum,
        validation_size=args.validation_size,
        seed=args.seed,
        num_workers=args.num_workers,
        skip_original=args.skip_original,
        skip_aps=args.skip_aps,
        save_auxiliary_outputs=args.save_auxiliary_outputs,
        evaluate_metrics=args.evaluate_metrics,
    )


if __name__ == "__main__":
    main()
