"""Attack Success Rate (ASR) for Data Attribution Depletion Attacks.

For each clean/poisoned pair (c_i, p_i), Formula 7 counts success when:

    s_p < s_c  OR  s_p * s_c < 0

The first condition is Gain-Stealing and the second is Loss-Amplifying.
The script supports the mapping formats generated by PPIS, APIS, APS, and
HTBM/HTBA.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import Dict, List, Optional

from Data_Attribution_Metrics_Common import (
    add_metric_input_arguments,
    load_sample_pairs,
    read_shapley_csv,
    write_json_result,
)


def compute_attack_success_rate(
    clean_shapley_path: Path,
    poisoned_shapley_path: Path,
    mapping_path: Path,
    pair_mode: str = "auto",
    append_offset: Optional[int] = None,
    magnitude_threshold: float = 0.0,
    details_output: Optional[Path] = None,
) -> Dict[str, object]:
    """Compute Formula 7 and return a JSON-serializable summary."""

    if magnitude_threshold < 0.0:
        raise ValueError("magnitude_threshold must be non-negative.")

    clean_scores = read_shapley_csv(clean_shapley_path)
    poisoned_scores = read_shapley_csv(poisoned_shapley_path)
    pairs = load_sample_pairs(
        mapping_path=mapping_path,
        clean_scores=clean_scores,
        poison_scores=poisoned_scores,
        pair_mode=pair_mode,
        append_offset=append_offset,
    )

    details: List[Dict[str, object]] = []
    success_count = 0
    gain_stealing_count = 0
    loss_amplifying_count = 0
    gain_only_count = 0
    loss_only_count = 0
    both_count = 0

    for pair in pairs:
        clean_value = clean_scores[pair.clean_index]
        poisoned_value = poisoned_scores[pair.poison_index]

        gain_stealing = poisoned_value < clean_value
        if magnitude_threshold > 0.0 and gain_stealing:
            required_drop = magnitude_threshold * max(abs(clean_value), 1e-12)
            gain_stealing = (
                clean_value - poisoned_value >= required_drop
            )
        loss_amplifying = poisoned_value * clean_value < 0.0
        success = gain_stealing or loss_amplifying

        gain_stealing_count += int(gain_stealing)
        loss_amplifying_count += int(loss_amplifying)
        if gain_stealing and loss_amplifying:
            both_count += 1
        elif gain_stealing:
            gain_only_count += 1
        elif loss_amplifying:
            loss_only_count += 1
        success_count += int(success)

        details.append(
            {
                "clean_index": pair.clean_index,
                "poison_index": pair.poison_index,
                "clean_shapley": clean_value,
                "poisoned_shapley": poisoned_value,
                "delta_poison_minus_clean": poisoned_value - clean_value,
                "gain_stealing": int(gain_stealing),
                "loss_amplifying": int(loss_amplifying),
                "attack_success": int(success),
            }
        )

    total = len(pairs)
    asr = success_count / total if total else 0.0
    result: Dict[str, object] = {
        "metric": "ASR",
        "attack_success_rate": asr,
        "success_count": success_count,
        "pair_count": total,
        "gain_stealing_count": gain_stealing_count,
        "loss_amplifying_count": loss_amplifying_count,
        "gain_stealing_only_count": gain_only_count,
        "loss_amplifying_only_count": loss_only_count,
        "both_conditions_count": both_count,
        "magnitude_threshold": magnitude_threshold,
        "clean_shapley": str(clean_shapley_path),
        "poisoned_shapley": str(poisoned_shapley_path),
        "mapping": str(mapping_path),
        "formula": "mean(I(sp < sc or sp * sc < 0))",
    }

    if details_output is not None:
        details_path = Path(details_output)
        details_path.parent.mkdir(parents=True, exist_ok=True)
        with details_path.open("w", newline="", encoding="utf-8") as output_file:
            writer = csv.DictWriter(
                output_file,
                fieldnames=list(details[0].keys()) if details else [
                    "clean_index",
                    "poison_index",
                    "clean_shapley",
                    "poisoned_shapley",
                    "delta_poison_minus_clean",
                    "gain_stealing",
                    "loss_amplifying",
                    "attack_success",
                ],
            )
            writer.writeheader()
            writer.writerows(details)
        result["details_output"] = str(details_path)

    return result


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Compute Formula 7 Attack Success Rate (ASR)."
    )
    add_metric_input_arguments(parser, mapping_required=True)
    parser.add_argument(
        "--magnitude-threshold",
        type=float,
        default=0.0,
        help=(
            "Optional relative drop required for Gain-Stealing. "
            "0 keeps the paper's binary ASR definition."
        ),
    )
    parser.add_argument(
        "--details-output",
        type=Path,
        default=None,
        help="Optional per-pair CSV output.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    result = compute_attack_success_rate(
        clean_shapley_path=args.clean_shapley,
        poisoned_shapley_path=args.poisoned_shapley,
        mapping_path=args.mapping,
        pair_mode=args.pair_mode,
        append_offset=args.append_offset,
        magnitude_threshold=args.magnitude_threshold,
        details_output=args.details_output,
    )
    output_path = write_json_result(
        result=result,
        output_path=args.output,
        default_directory=args.clean_shapley.parent,
        default_name="asr_result.json",
    )
    print(f"ASR = {float(result['attack_success_rate']):.6f}")
    print(
        f"Successful pairs: {result['success_count']}/"
        f"{result['pair_count']}"
    )
    print(f"Result JSON: {output_path}")


if __name__ == "__main__":
    main()
