"""
First-order In-Run Data Shapley (IRDS) flow for APIS.

This script consumes:

1. The YouTube Aligned Face identity dataset.
2. The APIS poisoned samples and ``apis_mapping.csv`` generated by
   Backdoor_Poisoning_Strategy_APIS.py.

It trains two victim-side identity classifiers and writes exactly the two
Shapley-value CSV files needed by the downstream metric code:

    shapley_original_APIS.csv
    shapley_apis.csv

No GSR/LAR/GVR/ASR evaluation is implemented here by design.
"""

from __future__ import annotations

import argparse
import csv
import random
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Mapping, Optional, Sequence, Tuple

import numpy as np
from PIL import Image

import torch
import torch.nn as nn
import torch.optim as optim
from torch.nn.utils import parameters_to_vector
from torch.utils.data import DataLoader, Dataset, Subset

from Backdoor_Poisoning_Strategy_APIS import FaceSample, discover_imagefolder_samples


FACE_MEAN = (0.5, 0.5, 0.5)
FACE_STD = (0.5, 0.5, 0.5)


@dataclass(frozen=True)
class APISPoisonRecord:
    original_index: int
    original_label: int
    poisoned_label: int
    poisoned_path: Path


def set_seed(seed: int = 42) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


def image_to_tensor(
    image_path: Path,
    image_size: Tuple[int, int],
    mean: Sequence[float] = FACE_MEAN,
    std: Sequence[float] = FACE_STD,
) -> torch.Tensor:
    """Load one RGB face image and return a normalized [C,H,W] tensor."""

    image = Image.open(image_path).convert("RGB").resize(
        image_size,
        Image.Resampling.BILINEAR,
    )
    array = np.asarray(image, dtype=np.float32).copy() / 255.0
    tensor = torch.from_numpy(array).permute(2, 0, 1)
    mean_tensor = torch.tensor(mean, dtype=tensor.dtype).view(3, 1, 1)
    std_tensor = torch.tensor(std, dtype=tensor.dtype).view(3, 1, 1)
    return (tensor - mean_tensor) / std_tensor


class IndexedYouTubeFaceDataset(Dataset):
    """Return ``(global_sample_index, image_tensor, identity_label)``."""

    def __init__(
        self,
        samples: Sequence[FaceSample],
        image_size: Tuple[int, int] = (47, 55),
    ) -> None:
        self.samples = list(samples)
        self.image_size = image_size

    def __len__(self) -> int:
        return len(self.samples)

    def __getitem__(self, position: int):
        sample = self.samples[position]
        image = image_to_tensor(sample.path, self.image_size)
        return sample.index, image, sample.label


class APISPoisonedYouTubeFaceDataset(Dataset):
    """Replace selected samples by APIS images and target labels."""

    def __init__(
        self,
        clean_dataset: IndexedYouTubeFaceDataset,
        poison_records: Mapping[int, APISPoisonRecord],
        label_mode: str = "poisoned",
    ) -> None:
        if label_mode not in {"poisoned", "original"}:
            raise ValueError("label_mode must be 'poisoned' or 'original'.")
        self.clean_dataset = clean_dataset
        self.poison_records = dict(poison_records)
        self.label_mode = label_mode

    def __len__(self) -> int:
        return len(self.clean_dataset)

    def __getitem__(self, position: int):
        sample = self.clean_dataset.samples[position]
        record = self.poison_records.get(sample.index)
        if record is None:
            return self.clean_dataset[position]

        label = (
            record.poisoned_label
            if self.label_mode == "poisoned"
            else record.original_label
        )
        image = image_to_tensor(record.poisoned_path, self.clean_dataset.image_size)
        return sample.index, image, label


class YouTubeFaceCNN(nn.Module):
    """A compact RGB face classifier for 47 x 55 aligned faces."""

    def __init__(self, num_classes: int, feature_dim: int = 128) -> None:
        super().__init__()
        self.features = nn.Sequential(
            nn.Conv2d(3, 32, kernel_size=3, padding=1),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2),
            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2),
            nn.Conv2d(64, feature_dim, kernel_size=3, padding=1),
            nn.ReLU(inplace=True),
            nn.AdaptiveAvgPool2d((1, 1)),
        )
        self.classifier = nn.Linear(feature_dim, num_classes)

    def forward(self, images: torch.Tensor) -> torch.Tensor:
        features = self.features(images)
        return self.classifier(features.flatten(1))


def load_apis_mapping(
    apis_root: Path,
    samples_by_index: Mapping[int, FaceSample],
    num_classes: int,
    label_mode: str = "poisoned",
) -> Dict[int, APISPoisonRecord]:
    """Read APIS poisoned-image replacements from apis_mapping.csv."""

    mapping_path = apis_root / "apis_mapping.csv"
    if not mapping_path.is_file():
        raise FileNotFoundError(
            f"APIS mapping not found: {mapping_path}. "
            "Run Backdoor_Poisoning_Strategy_APIS.py first."
        )

    records: Dict[int, APISPoisonRecord] = {}
    with mapping_path.open("r", newline="", encoding="utf-8") as mapping_file:
        reader = csv.DictReader(mapping_file)
        required = {
            "original_index",
            "original_label",
            "poisoned_label",
            "poisoned_path",
        }
        missing = required.difference(reader.fieldnames or [])
        if missing:
            raise ValueError(
                f"apis_mapping.csv is missing columns: {', '.join(sorted(missing))}"
            )

        for row in reader:
            original_index = int(row["original_index"])
            original_label = int(row["original_label"])
            poisoned_label = int(row["poisoned_label"])
            if original_index not in samples_by_index:
                raise ValueError(
                    f"Mapping sample {original_index} is not present in the "
                    "current retained dataset. Check min_images_per_identity."
                )
            expected_label = samples_by_index[original_index].label
            if expected_label != original_label:
                raise ValueError(
                    f"Label mismatch for sample {original_index}: "
                    f"mapping={original_label}, dataset={expected_label}."
                )
            if not 0 <= poisoned_label < num_classes:
                raise ValueError(
                    f"Poisoned label {poisoned_label} for sample {original_index} "
                    f"is outside [0, {num_classes})."
                )

            poisoned_path = Path(row["poisoned_path"])
            if not poisoned_path.is_absolute():
                poisoned_path = apis_root / poisoned_path
            if not poisoned_path.is_file():
                raise FileNotFoundError(f"Poisoned APIS image not found: {poisoned_path}")

            records[original_index] = APISPoisonRecord(
                original_index=original_index,
                original_label=original_label,
                poisoned_label=poisoned_label,
                poisoned_path=poisoned_path,
            )

    if not records:
        raise ValueError(f"No APIS poison records were found in: {mapping_path}")
    return records


def choose_positions(
    samples: Sequence[FaceSample],
    seed: int,
    max_samples_per_identity: Optional[int] = None,
    max_total_samples: Optional[int] = None,
) -> List[int]:
    """Select dataset positions while keeping FaceSample.index unchanged."""

    rng = random.Random(seed)
    positions = list(range(len(samples)))

    if max_samples_per_identity is not None:
        if max_samples_per_identity <= 0:
            raise ValueError("max_samples_per_identity must be positive.")
        by_label: Dict[int, List[int]] = {}
        for position, sample in enumerate(samples):
            by_label.setdefault(sample.label, []).append(position)
        positions = []
        for label in sorted(by_label):
            label_positions = by_label[label]
            if len(label_positions) > max_samples_per_identity:
                label_positions = sorted(
                    rng.sample(label_positions, max_samples_per_identity)
                )
            positions.extend(label_positions)
        positions = sorted(positions)

    if max_total_samples is not None:
        if max_total_samples <= 0:
            raise ValueError("max_total_samples must be positive.")
        if len(positions) > max_total_samples:
            positions = sorted(rng.sample(positions, max_total_samples))

    return positions


def choose_validation_positions(
    candidate_positions: Sequence[int],
    validation_size: int,
    seed: int,
) -> List[int]:
    if validation_size <= 0:
        raise ValueError("validation_size must be positive.")
    if not candidate_positions:
        raise ValueError("No candidate positions are available.")
    rng = random.Random(seed)
    size = min(validation_size, len(candidate_positions))
    return sorted(rng.sample(list(candidate_positions), size))


def merge_required_positions(
    selected_positions: Sequence[int],
    required_positions: Sequence[int],
) -> List[int]:
    """Return a sorted selection that includes every required position."""

    return sorted(set(selected_positions).union(required_positions))


def build_validation_batch(
    clean_dataset: IndexedYouTubeFaceDataset,
    validation_positions: Sequence[int],
    device: torch.device,
) -> Tuple[torch.Tensor, torch.Tensor]:
    images: List[torch.Tensor] = []
    labels: List[int] = []
    for position in validation_positions:
        _, image, label = clean_dataset[position]
        images.append(image)
        labels.append(int(label))
    return torch.stack(images).to(device), torch.tensor(labels, dtype=torch.long).to(device)


def _flatten_gradient_dict(gradients: Mapping[str, torch.Tensor]) -> torch.Tensor:
    return torch.cat(
        [gradient.reshape(gradient.size(0), -1) for gradient in gradients.values()],
        dim=1,
    )


def per_sample_grads(
    model: nn.Module,
    images: torch.Tensor,
    labels: torch.Tensor,
    criterion: nn.Module,
) -> torch.Tensor:
    """Compute one flattened parameter gradient per sample."""

    try:
        from torch.func import functional_call, grad, vmap

        params = dict(model.named_parameters())
        buffers = dict(model.named_buffers())

        def loss_fn(functional_params, functional_buffers, image, label):
            logits = functional_call(
                model,
                (functional_params, functional_buffers),
                (image.unsqueeze(0),),
            )
            return criterion(logits, label.unsqueeze(0))

        gradients = vmap(grad(loss_fn), (None, None, 0, 0))(
            params,
            buffers,
            images,
            labels,
        )
        return _flatten_gradient_dict(gradients)
    except (ImportError, RuntimeError, TypeError):
        parameters = tuple(
            parameter for parameter in model.parameters() if parameter.requires_grad
        )
        flat_gradients: List[torch.Tensor] = []
        for image, label in zip(images, labels):
            logits = model(image.unsqueeze(0))
            loss = criterion(logits, label.unsqueeze(0))
            gradients = torch.autograd.grad(
                loss,
                parameters,
                create_graph=False,
                retain_graph=False,
                allow_unused=True,
            )
            flat_gradients.append(
                torch.cat(
                    [
                        torch.zeros_like(parameter).reshape(-1)
                        if gradient is None
                        else gradient.reshape(-1)
                        for parameter, gradient in zip(parameters, gradients)
                    ]
                )
            )
        return torch.stack(flat_gradients, dim=0)


def compute_validation_gradient(
    model: nn.Module,
    val_images: torch.Tensor,
    val_labels: torch.Tensor,
    criterion: nn.Module,
) -> torch.Tensor:
    """Compute the flattened validation loss gradient used by IRDS."""

    parameters = tuple(
        parameter for parameter in model.parameters() if parameter.requires_grad
    )
    was_training = model.training
    model.train()
    try:
        logits = model(val_images)
        val_loss = criterion(logits, val_labels)
        gradients = torch.autograd.grad(
            val_loss,
            parameters,
            create_graph=False,
            retain_graph=False,
            allow_unused=True,
        )
        filled = [
            torch.zeros_like(parameter) if gradient is None else gradient
            for parameter, gradient in zip(parameters, gradients)
        ]
        return parameters_to_vector(filled).detach().unsqueeze(0)
    finally:
        model.train(was_training)


def train_and_compute_shapley(
    model: nn.Module,
    train_loader: DataLoader,
    optimizer: optim.Optimizer,
    criterion: nn.Module,
    epochs: int,
    device: torch.device,
    val_images: torch.Tensor,
    val_labels: torch.Tensor,
    global_sample_count: int,
    shapley_path: Path,
    model_name: str,
) -> Path:
    """Train one model and save first-order in-run data Shapley values."""

    data_shapley = torch.zeros(global_sample_count, device=device)
    print(f"Training {model_name} and accumulating first-order IRDS values...")

    for epoch in range(epochs):
        model.train()
        running_loss = 0.0
        correct = 0
        total = 0

        for indices, images, labels in train_loader:
            indices = indices.to(device, dtype=torch.long)
            images = images.to(device, non_blocking=True)
            labels = labels.to(device, non_blocking=True)

            sample_gradients = per_sample_grads(model, images, labels, criterion)
            validation_gradient = compute_validation_gradient(
                model,
                val_images,
                val_labels,
                criterion,
            )
            learning_rate = float(optimizer.param_groups[0]["lr"])
            shapley_increment = -learning_rate * (
                sample_gradients @ validation_gradient.T
            ).squeeze(1)
            data_shapley[indices] += shapley_increment.detach()

            optimizer.zero_grad(set_to_none=True)
            logits = model(images)
            loss = criterion(logits, labels)
            loss.backward()
            optimizer.step()

            running_loss += float(loss.item()) * labels.size(0)
            correct += int((logits.argmax(dim=1) == labels).sum().item())
            total += labels.size(0)

        train_loss = running_loss / max(total, 1)
        train_acc = 100.0 * correct / max(total, 1)
        print(
            f"[{model_name}] Epoch {epoch + 1:03d}/{epochs:03d} | "
            f"Train Loss {train_loss:.4f} | Train Acc {train_acc:.2f}%"
        )

    shapley_path.parent.mkdir(parents=True, exist_ok=True)
    with shapley_path.open("w", newline="", encoding="utf-8") as output_file:
        writer = csv.writer(output_file)
        writer.writerow(["sample_index", "shapley_value"])
        for index, value in enumerate(data_shapley.detach().cpu().tolist()):
            writer.writerow([index, float(value)])
    print(f"{model_name} Shapley values saved to: {shapley_path}")
    return shapley_path


def make_loader(
    dataset: Dataset,
    train_positions: Sequence[int],
    batch_size: int,
    seed: int,
    device: torch.device,
    num_workers: int,
) -> DataLoader:
    generator = torch.Generator()
    generator.manual_seed(seed)
    return DataLoader(
        Subset(dataset, list(train_positions)),
        batch_size=batch_size,
        shuffle=True,
        generator=generator,
        num_workers=num_workers,
        pin_memory=device.type == "cuda",
    )


def run_apis_irds(
    dataset_root: Path,
    apis_root: Path,
    output_dir: Path,
    image_size: Tuple[int, int] = (47, 55),
    min_images_per_identity: int = 100,
    epochs: int = 100,
    batch_size: int = 32,
    learning_rate: float = 0.01,
    momentum: float = 0.9,
    validation_size: int = 128,
    seed: int = 42,
    num_workers: int = 0,
    feature_dim: int = 128,
    max_samples_per_identity: Optional[int] = None,
    max_total_samples: Optional[int] = None,
    exclude_validation_from_training: bool = True,
    label_mode: str = "poisoned",
    skip_original: bool = False,
    skip_apis: bool = False,
) -> Tuple[Optional[Path], Optional[Path]]:
    """Run clean and APIS-poisoned IRDS training."""

    if skip_original and skip_apis:
        raise ValueError("At least one of skip_original and skip_apis must be False.")
    if epochs <= 0:
        raise ValueError("epochs must be positive.")
    if batch_size <= 0:
        raise ValueError("batch_size must be positive.")

    set_seed(seed)
    samples, class_names = discover_imagefolder_samples(
        dataset_root=dataset_root,
        min_images_per_identity=min_images_per_identity,
    )
    samples_by_index = {sample.index: sample for sample in samples}
    if len(samples_by_index) != len(samples):
        raise ValueError("Sample indices are not unique.")
    position_by_index = {
        sample.index: position
        for position, sample in enumerate(samples)
    }
    poison_records = load_apis_mapping(
        apis_root=apis_root,
        samples_by_index=samples_by_index,
        num_classes=len(class_names),
        label_mode=label_mode,
    )
    poison_positions = sorted(
        position_by_index[index]
        for index in poison_records
        if index in position_by_index
    )

    selected_positions = choose_positions(
        samples,
        seed=seed,
        max_samples_per_identity=max_samples_per_identity,
        max_total_samples=max_total_samples,
    )
    before_merge = len(selected_positions)
    selected_positions = merge_required_positions(
        selected_positions,
        poison_positions,
    )
    if len(selected_positions) != before_merge:
        print(
            "Added APIS poison-record positions to the training candidate set: "
            f"{len(selected_positions) - before_merge}"
        )

    validation_candidates = list(selected_positions)
    if exclude_validation_from_training:
        poison_position_set = set(poison_positions)
        non_poison_candidates = [
            position
            for position in selected_positions
            if position not in poison_position_set
        ]
        if non_poison_candidates:
            validation_candidates = non_poison_candidates

    validation_positions = choose_validation_positions(
        validation_candidates,
        validation_size=validation_size,
        seed=seed + 1,
    )
    if exclude_validation_from_training:
        validation_set = set(validation_positions)
        train_positions = [
            position for position in selected_positions if position not in validation_set
        ]
        train_positions = merge_required_positions(train_positions, poison_positions)
    else:
        train_positions = list(selected_positions)
    if not train_positions:
        raise ValueError("No training positions are available.")

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"APIS IRDS device: {device}")
    print(
        f"Retained identities: {len(class_names)}, total samples: {len(samples)}, "
        f"train positions: {len(train_positions)}, validation size: {len(validation_positions)}"
    )

    clean_dataset = IndexedYouTubeFaceDataset(samples, image_size=image_size)
    active_poison_indices = {
        clean_dataset.samples[position].index
        for position in train_positions
    }.intersection(poison_records)
    print(
        f"APIS replacements active in training: "
        f"{len(active_poison_indices)} / {len(poison_records)} mapping records"
    )

    poisoned_dataset = APISPoisonedYouTubeFaceDataset(
        clean_dataset=clean_dataset,
        poison_records=poison_records,
        label_mode=label_mode,
    )
    val_images, val_labels = build_validation_batch(
        clean_dataset,
        validation_positions,
        device,
    )
    criterion = nn.CrossEntropyLoss(reduction="mean")
    global_sample_count = max(sample.index for sample in samples) + 1
    output_dir.mkdir(parents=True, exist_ok=True)

    original_path: Optional[Path] = None
    apis_path: Optional[Path] = None

    if not skip_original:
        set_seed(seed)
        clean_loader = make_loader(
            clean_dataset,
            train_positions,
            batch_size,
            seed,
            device,
            num_workers,
        )
        clean_model = YouTubeFaceCNN(
            num_classes=len(class_names),
            feature_dim=feature_dim,
        ).to(device)
        clean_optimizer = optim.SGD(
            clean_model.parameters(),
            lr=learning_rate,
            momentum=momentum,
        )
        original_path = train_and_compute_shapley(
            model=clean_model,
            train_loader=clean_loader,
            optimizer=clean_optimizer,
            criterion=criterion,
            epochs=epochs,
            device=device,
            val_images=val_images,
            val_labels=val_labels,
            global_sample_count=global_sample_count,
            shapley_path=output_dir / "shapley_original_APIS.csv",
            model_name="Original_APIS",
        )

    if not skip_apis:
        set_seed(seed)
        poisoned_loader = make_loader(
            poisoned_dataset,
            train_positions,
            batch_size,
            seed,
            device,
            num_workers,
        )
        poisoned_model = YouTubeFaceCNN(
            num_classes=len(class_names),
            feature_dim=feature_dim,
        ).to(device)
        poisoned_optimizer = optim.SGD(
            poisoned_model.parameters(),
            lr=learning_rate,
            momentum=momentum,
        )
        apis_path = train_and_compute_shapley(
            model=poisoned_model,
            train_loader=poisoned_loader,
            optimizer=poisoned_optimizer,
            criterion=criterion,
            epochs=epochs,
            device=device,
            val_images=val_images,
            val_labels=val_labels,
            global_sample_count=global_sample_count,
            shapley_path=output_dir / "shapley_apis.csv",
            model_name="APIS",
        )

    return original_path, apis_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Compute clean/APIS first-order IRDS Shapley CSV files."
    )
    parser.add_argument("--dataset-root", type=Path, required=True)
    parser.add_argument(
        "--apis-root",
        type=Path,
        required=True,
        help="Directory containing apis_mapping.csv and APIS poisoned images.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Defaults to <apis-root>/irds_results.",
    )
    parser.add_argument(
        "--image-size",
        type=int,
        nargs=2,
        metavar=("WIDTH", "HEIGHT"),
        default=(47, 55),
    )
    parser.add_argument("--min-images-per-identity", type=int, default=100)
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--batch-size", type=int, default=32)
    parser.add_argument("--learning-rate", type=float, default=0.01)
    parser.add_argument("--momentum", type=float, default=0.9)
    parser.add_argument("--validation-size", type=int, default=128)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--num-workers", type=int, default=0)
    parser.add_argument("--feature-dim", type=int, default=128)
    parser.add_argument("--max-samples-per-identity", type=int, default=None)
    parser.add_argument("--max-total-samples", type=int, default=None)
    validation_group = parser.add_mutually_exclusive_group()
    validation_group.add_argument(
        "--exclude-validation-from-training",
        dest="exclude_validation_from_training",
        action="store_true",
        default=True,
        help="Use a held-out clean validation subset (default).",
    )
    validation_group.add_argument(
        "--include-validation-in-training",
        dest="exclude_validation_from_training",
        action="store_false",
        help="Allow validation samples to also participate in training.",
    )
    parser.add_argument(
        "--label-mode",
        choices=("poisoned", "original"),
        default="poisoned",
        help="APIS backdoor training normally uses poisoned target labels.",
    )
    parser.add_argument("--skip-original", action="store_true")
    parser.add_argument("--skip-apis", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    output_dir = args.output_dir or (args.apis_root / "irds_results")
    original_path, apis_path = run_apis_irds(
        dataset_root=args.dataset_root,
        apis_root=args.apis_root,
        output_dir=output_dir,
        image_size=tuple(args.image_size),
        min_images_per_identity=args.min_images_per_identity,
        epochs=args.epochs,
        batch_size=args.batch_size,
        learning_rate=args.learning_rate,
        momentum=args.momentum,
        validation_size=args.validation_size,
        seed=args.seed,
        num_workers=args.num_workers,
        feature_dim=args.feature_dim,
        max_samples_per_identity=args.max_samples_per_identity,
        max_total_samples=args.max_total_samples,
        exclude_validation_from_training=args.exclude_validation_from_training,
        label_mode=args.label_mode,
        skip_original=args.skip_original,
        skip_apis=args.skip_apis,
    )
    if original_path is not None:
        print(f"Clean IRDS CSV: {original_path}")
    if apis_path is not None:
        print(f"APIS IRDS CSV: {apis_path}")


if __name__ == "__main__":
    main()
